Change FxViewData::rootNode type from Parent to Object
quarkiverse/quarkus-fx pull request #77
Opened 2024-10-08 05:58 UTC by Eng-Fouad

Fixes #76

2024-10-09 13:27 UTC, CodeSimcoe requested changes
Hello and thanks.

Consider adding some test cases ?

2024-10-09 13:27 UTC, CodeSimcoe commented on runtime/src/main/java/io/quarkiverse/fx/views/FxViewRepository.java
> +    private static ObservableList<String> getFxmlObjectStyleSheets(Object rootNode) {
```suggestion
    private static ObservableList<String> getFxmlObjectStyleSheets(final Object rootNode) {
```

2024-10-09 13:27 UTC, CodeSimcoe commented on runtime/src/main/java/io/quarkiverse/fx/views/FxViewRepository.java
> +        ObservableList<String> stylesheets = null;
```suggestion
        ObservableList<String> stylesheets;
```

2024-10-09 13:27 UTC, CodeSimcoe commented on runtime/src/main/java/io/quarkiverse/fx/views/FxViewRepository.java
> +        }
```suggestion
        } else {
          stylesheets = null;
        }
```

2024-10-09 13:27 UTC, CodeSimcoe commented on runtime/src/main/java/io/quarkiverse/fx/views/FxViewRepository.java
> +        }
Java 21 would have allowed us to use pattern matching here :/

2024-10-10 00:28 UTC, Eng-Fouad commented
> Hello and thanks.
> 
> Consider adding some test cases ?

Done.

2024-10-14 18:51 UTC, CodeSimcoe approved these changes
Thanks !

2024-10-14 18:51 UTC, merged

2024-10-14 18:53 UTC, CodeSimcoe commented
https://github.com/all-contributors add @Eng-Fouad for code

2024-10-14 18:54 UTC, CodeSimcoe commented
@all-contributors add @Eng-Fouad for code